controller_list:
  - name: fake_hephaestus_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
initial:  # Define initial robot poses per group
  - group: hephaestus_arm_group
    pose: home