joint_names:
  - j1
  - j2
  - j3
  - j4
  - j5
  - j6
  
joint_limits:
    j1:
      has_position_limits: true
      min_position: -3.14
      max_position: 3.14
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    j2:
      has_position_limits: true
      min_position: -3.14
      max_position: 3.14
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    j3:
      has_position_limits: true
      min_position: -3.14
      max_position: 3.14
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    j4:
      has_position_limits: true
      min_position: -3.14
      max_position: 3.14
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    j5:
      has_position_limits: true
      min_position: -3.14
      max_position: 3.14
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    j6:
      has_position_limits: true
      min_position: -1.57
      max_position: 1.57
      has_velocity_limits: true
      max_velocity: 3.0
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
